// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParcInformatiqueApp.Data;

#nullable disable

namespace ParcInformatiqueApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260819140826_SyncModelChanges")]
    partial class SyncModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParcInformatiqueApp.Models.Affectation", b =>
                {
                    b.Property<int>("IdAffectation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAffectation"));

                    b.Property<DateTime>("DateAffectation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRetour")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeIdEmploye")
                        .HasColumnType("int");

                    b.Property<int?>("EquipementIdEquipement")
                        .HasColumnType("int");

                    b.Property<int>("IdEmploye")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipement")
                        .HasColumnType("int");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAffectation");

                    b.HasIndex("EmployeIdEmploye");

                    b.HasIndex("EquipementIdEquipement");

                    b.ToTable("Affectations");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.Employe", b =>
                {
                    b.Property<int>("IdEmploye")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmploye"));

                    b.Property<int?>("IdLocalisation")
                        .HasColumnType("int");

                    b.Property<int>("IdService")
                        .HasColumnType("int");

                    b.Property<int?>("LocalisationIdLocalisation")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServiceIdService")
                        .HasColumnType("int");

                    b.HasKey("IdEmploye");

                    b.HasIndex("LocalisationIdLocalisation");

                    b.HasIndex("ServiceIdService");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.Equipement", b =>
                {
                    b.Property<int>("IdEquipement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipement"));

                    b.Property<DateTime>("DateAchat")
                        .HasColumnType("datetime2");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinGarantie")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fournisseur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLocalisation")
                        .HasColumnType("int");

                    b.Property<int>("IdType")
                        .HasColumnType("int");

                    b.Property<int?>("LocalisationIdLocalisation")
                        .HasColumnType("int");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomEquipement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeEquipementIdType")
                        .HasColumnType("int");

                    b.HasKey("IdEquipement");

                    b.HasIndex("LocalisationIdLocalisation");

                    b.HasIndex("TypeEquipementIdType");

                    b.ToTable("Equipements");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.InstallationLogiciel", b =>
                {
                    b.Property<int>("IdInstallation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInstallation"));

                    b.Property<DateTime>("DateInstallation")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EquipementIdEquipement")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipement")
                        .HasColumnType("int");

                    b.Property<int>("IdLogiciel")
                        .HasColumnType("int");

                    b.Property<int?>("LogicielIdLogiciel")
                        .HasColumnType("int");

                    b.Property<string>("VersionInstallee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdInstallation");

                    b.HasIndex("EquipementIdEquipement");

                    b.HasIndex("LogicielIdLogiciel");

                    b.ToTable("InstallationsLogiciels");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.Localisation", b =>
                {
                    b.Property<int>("IdLocalisation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocalisation"));

                    b.Property<string>("Batiment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NbBureau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLocalisation");

                    b.ToTable("Localisations");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.Logiciel", b =>
                {
                    b.Property<int>("IdLogiciel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLogiciel"));

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Licence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomLogiciel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLogiciel");

                    b.ToTable("Logiciels");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.Service", b =>
                {
                    b.Property<int>("IdService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdService"));

                    b.Property<string>("NomService")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdService");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.Ticket", b =>
                {
                    b.Property<int>("IdTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTicket"));

                    b.Property<string>("ActionRealisee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCloture")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnostic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EquipementIdEquipement")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipement")
                        .HasColumnType("int");

                    b.Property<int>("IdUserCreateur")
                        .HasColumnType("int");

                    b.Property<int?>("IdUserTraiteur")
                        .HasColumnType("int");

                    b.Property<string>("NomTicket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priorite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeIntervention")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTicket");

                    b.HasIndex("EquipementIdEquipement");

                    b.HasIndex("IdEquipement");

                    b.HasIndex("IdUserCreateur");

                    b.HasIndex("IdUserTraiteur");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.TypeEquipement", b =>
                {
                    b.Property<int>("IdType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdType"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdType");

                    b.ToTable("TypesEquipements");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmploye")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatutCompte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.HasIndex("IdEmploye")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.Affectation", b =>
                {
                    b.HasOne("ParcInformatiqueApp.Models.Employe", "Employe")
                        .WithMany("Affectations")
                        .HasForeignKey("EmployeIdEmploye");

                    b.HasOne("ParcInformatiqueApp.Models.Equipement", "Equipement")
                        .WithMany("Affectations")
                        .HasForeignKey("EquipementIdEquipement");

                    b.Navigation("Employe");

                    b.Navigation("Equipement");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.Employe", b =>
                {
                    b.HasOne("ParcInformatiqueApp.Models.Localisation", "Localisation")
                        .WithMany("Employes")
                        .HasForeignKey("LocalisationIdLocalisation");

                    b.HasOne("ParcInformatiqueApp.Models.Service", "Service")
                        .WithMany("Employes")
                        .HasForeignKey("ServiceIdService");

                    b.Navigation("Localisation");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.Equipement", b =>
                {
                    b.HasOne("ParcInformatiqueApp.Models.Localisation", "Localisation")
                        .WithMany("Equipements")
                        .HasForeignKey("LocalisationIdLocalisation");

                    b.HasOne("ParcInformatiqueApp.Models.TypeEquipement", "TypeEquipement")
                        .WithMany("Equipements")
                        .HasForeignKey("TypeEquipementIdType");

                    b.Navigation("Localisation");

                    b.Navigation("TypeEquipement");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.InstallationLogiciel", b =>
                {
                    b.HasOne("ParcInformatiqueApp.Models.Equipement", "Equipement")
                        .WithMany("Installations")
                        .HasForeignKey("EquipementIdEquipement");

                    b.HasOne("ParcInformatiqueApp.Models.Logiciel", "Logiciel")
                        .WithMany("Installations")
                        .HasForeignKey("LogicielIdLogiciel");

                    b.Navigation("Equipement");

                    b.Navigation("Logiciel");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.Ticket", b =>
                {
                    b.HasOne("ParcInformatiqueApp.Models.Equipement", null)
                        .WithMany("Tickets")
                        .HasForeignKey("EquipementIdEquipement");

                    b.HasOne("ParcInformatiqueApp.Models.Equipement", "Equipement")
                        .WithMany()
                        .HasForeignKey("IdEquipement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParcInformatiqueApp.Models.User", "UserCreateur")
                        .WithMany("TicketsCrees")
                        .HasForeignKey("IdUserCreateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ParcInformatiqueApp.Models.User", "UserTraiteur")
                        .WithMany("TicketsTraites")
                        .HasForeignKey("IdUserTraiteur")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Equipement");

                    b.Navigation("UserCreateur");

                    b.Navigation("UserTraiteur");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.User", b =>
                {
                    b.HasOne("ParcInformatiqueApp.Models.Employe", "Employe")
                        .WithOne("User")
                        .HasForeignKey("ParcInformatiqueApp.Models.User", "IdEmploye")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.Employe", b =>
                {
                    b.Navigation("Affectations");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.Equipement", b =>
                {
                    b.Navigation("Affectations");

                    b.Navigation("Installations");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.Localisation", b =>
                {
                    b.Navigation("Employes");

                    b.Navigation("Equipements");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.Logiciel", b =>
                {
                    b.Navigation("Installations");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.Service", b =>
                {
                    b.Navigation("Employes");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.TypeEquipement", b =>
                {
                    b.Navigation("Equipements");
                });

            modelBuilder.Entity("ParcInformatiqueApp.Models.User", b =>
                {
                    b.Navigation("TicketsCrees");

                    b.Navigation("TicketsTraites");
                });
#pragma warning restore 612, 618
        }
    }
}
